### ISSUE TITLE
Fixing the punctuation marks in Amazon subtitles

### ISSUE THREAD

**Issue by Essam311** [Paco8/ttml2ssa#2]
Hi, the punctuation marks in the Amazon subtitles for the Arabic language are not in its correct position (It worked fine with "script.module.ttml2ssa-0.3.2.zip" before).

You could test it in the Arabic subtitle of the movie "Back to the Future Part II" on primevideo, it looks like this.

![11](https://user-images.githubusercontent.com/59211054/111857993-11877600-893e-11eb-8984-28b906f5ea4b.png)

When it should look like this.

![22](https://user-images.githubusercontent.com/59211054/111857998-1815ed80-893e-11eb-9436-31770d9b212c.png)

**Comment by Paco8** [comment]
Unfortunately that movie is not available in my country. Could you send the subtitle file (or tell me another movie with this problem)?

**Comment by Essam311** [comment]
Here is the Arabic subtitle file for the movie "Back to the Future Part II" downloaded from primevideo.com in ttml2 format.

[Back.To.The.Future.II.zip](https://github.com/Paco8/ttml2ssa/files/6175063/Back.To.The.Future.II.zip)

**Comment by Paco8** [comment]
Could you test if this is fixed in version 0.3.4?

**Comment by Essam311** [comment]
Thank you so much, everything is working great now.
