### ISSUE TITLE
Subtitle Error

### ISSUE THREAD

**Issue by petersonti** [Paco8/ttml2ssa#3]
[Teste.pt.zip](https://github.com/Paco8/ttml2ssa/files/7532903/Teste.pt.zip)
This subtitle has error
Has possible joiner and merge same text?

**Comment by Paco8** [comment]
I think this is fixed in version 0.3.6.

**Comment by petersonti** [comment]
it is possible to fix the caption spaces in Windows
example on Windows:
`1

00:00:06,840 --> 00:00:07,807

♪ vinheta ♪



2

00:00:07,841 --> 00:00:08,000

♪ música de ação ♪

`

On Linux
`
1
00:00:06,840 --> 00:00:07,807
♪ vinheta ♪

2
00:00:07,841 --> 00:00:08,000
♪ música de ação ♪
`

**Comment by Paco8** [comment]
Hopefully this is fixed in version 0.3.7.

**Comment by petersonti** [comment]
The tool dont merge same text in vtt : Example:

[Dexter.txt](https://github.com/Paco8/ttml2ssa/files/7800474/Dexter.txt)

**Comment by Paco8** [comment]
Use the option `--no-fix-collisions`
