### ISSUE TITLE
Output .ssa files are malformed according to Aegisub

### ISSUE THREAD

**Issue by flagg19** [Paco8/ttml2ssa#6]
Hi there, I'm trying to edit the .ssa file produced by your tool, using Aegisub. It says the file is malformed:

![image](https://user-images.githubusercontent.com/1681032/181049292-fdefdce3-60a1-49f4-8d60-154767b041c2.png)

I also tried to load (without modification) the produced file in MPC-HC and if fails with no error.

Using a random online tool to do the conversion, this is what I've found:

> yours
```ssa
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, BackColour, OutlineColour, Bold, Italic, Alignment, BorderStyle, Outline, Shadow, MarginL, MarginR, MarginV
Style: Default,Arial,50,&H00FFFFFF,&H40000000,&H00000000,0,0,2,1,2,3,40,40,40

[Events]
Format: Layer, Start, End, Style, Text
Dialogue: 0,0:00:06.31,0:00:07.52,Default,{\i1}This doesn't work{\i0}
```

> another online tool
```ssa
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,monospace,20,&H00FFFFFF,&H0300FFFF,&H00000000,&H02000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:06.31,0:00:07.52,Default,,0,0,0,,{\i1}This works{\i0}
```

Other than minor differences in the style, the main difference is that yours lacks some format fields. It makes sense given the error message "not enought fields".

I'm no subtitle expert, I don't know what's the minimum set of fields required, here there's a good description of what they do but no mention if they are mandatory or not: https://forum.videohelp.com/attachment.php?attachmentid=33290&d=1440307546

Anyway, I'm forking (https://github.com/Paco8/ttml2ssa/compare/main...flagg19:ttml2ssa:main) and patching it up adding all missing fields with an empty/default value just to make it work because I need it. I'm opening this issue in case you didn't know and want to do a proper fix.

**Comment by YuenSzeHong** [comment]
great to find a fixing fork, but there is no working build as the release version is still 0.3.7, would you kindly release a version that fixes the problem?

**Comment by flagg19** [comment]
> great to find a fixing fork, but there is no working build as the release version is still 0.3.7, would you kindly release a version that fixes the problem?

here you go: https://github.com/flagg19/ttml2ssa/releases/tag/v0.3.7-fork

I haven't changed the version number because I don't know what's the proper etiquette for versions in forks

**Comment by YuenSzeHong** [comment]
thanks
